sudo: required
dist: xenial
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: WNoYXTLeLDk7cdCqaKKmpbQBzpAzuP3EqlWCjXhZjUlaRYRzJ6LE53JLwxrVlNafVvAy/uCXOVsor5pRSvQdD/uHvwnC4RwoMk3PCjc2DL7yqV/9NgpfwoeW+I2Y09bagxMtIda6WB3kOIYnC3FPszYzG+OUjoshsni6Dm6qRSoA1iLKCKph5zMg72n5nWqlFY5XwHJ9xx+lCzO4QXStOzTOUv7ycn7PRMAMCMaNJREHfZ60CPHT5/1nKS7L+SnUaLbwFlzuU4SeRrPcsMKYioCQeMV0Tvva014cttiak8Qi+RQsafMUPy/Wh810aD6qgiTTp+Ob/uZnmUx3rNEjOf+rZAWsFUWmyUMtpNV09zKrEx4hpQ8RyamUHcLKyyEo7AS+ZWiAw3dy8W1nPOn9mqliVK9m9orDRome/nFeR3MhJi0QTu/pTAsGdHYp3ZMtfPxjSsl2Efp6Ww36u2XEBSV87W7Is54OmykAXIOBQyVJq7AOLosbM+EbiFmR5oezZroPcy2fjr67OraoTQLlupftg+eVLR8vVYQUSWIS5u13HKDF5F9+QugYYJBaTTgThwlS1ISDL1qvSyj51lH1yuVhTdedXpJQfrIhyLv0OmLdIeG9mQUB5L1nrqTkLZo1z3RvorcH2TdckSFV537R136whs5/HNJdOrxqDUkhqCE=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: bIHCakAcDnUiHxrD2tLK6oSJMM73sw4SYA8aNtQJquoRiQI8tdiTqKlqaOpOzt1aBXOGJmFK8xtMeC+SN5KTRXnQyworC3F8rvI0RqJ62lZPHCihshPSXjhovljT84IRqM/YtloD2rdApphPm3JkUQcigok72JiWygBot4n8RDTZSlnpa8InGJezhUm4P9NEL07csO1eqtje13Zypdy1i6QmFzNNvd2MK5zWg0GmehWdy0algPngrhT6Wd4dg7iQGenmqtYAnLoLv9JaZwo5kVn3+uPRe2kyjVqjhzYi/HPwImZiXsoX4Cqxsek8EgmUUHrAZCNpfdKyeBc14B0JPl2lKgJuJwiMYGHOsZvjFOCsjSoKuWhGNeZMFvNJIosXD+Pnz9mb5EABVuO8qlKA7Oo40R+WbKYFKi6goxuNukJXDp00Yd4LeYGxUeBPTnV4rxUOMA8eSEhSqJhE+DF5Gbj0nbQAFhms/OB0CBoNC7CRopu7UBIVt1QpQRmxkLfwtydKLUcXJwPTCn5pwbZUYYNoNF0CRvYAEUwjAFDyFRQ1s3tQvflRwwkN/CcTagkP/XeX0NMs6+NqIhH3dlN/gkmYXcYYLcjJA5CljDtA7W+jVAiBkqqLsFhkWubvrpUEO2MA8Y81qygz0MeOfugUCa4SvtBjpAVS7CbSmnzhxDM=
